### NumPy vs. Python Lists – Performance Test
Let’s compare Python lists with NumPy arrays using a simple example

In [5]:
import numpy as np
import time

 # Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result = [x + y for x, y in zip(list1, list2)] # result = [0+0, 1+1, 2+2, ..., 999999+999999]
end = time.time()

print("Python list addition time:", end - start)


 # NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)
start = time.time()
result = arr1 + arr2  # Vectorized operation , result = [0+0, 1+1, 2+2, ..., 999999+999999]
end = time.time()
print("NumPy array addition time:", end - start)

Python list addition time: 0.12790131568908691
NumPy array addition time: 0.025894641876220703


What is zip() in Python?

* The zip() function takes two (or more) sequences (like lists) and pairs up their elements into tuples.

In [6]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

zipped = zip(list1, list2)
print(list(zipped))  # [(1, 4), (2, 5), (3, 6)]


[(1, 4), (2, 5), (3, 6)]


#  Creating NumPy Arrays

In [7]:
# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


## Memory Efficiency – NumPy vs. Lists

In [8]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


##  Vectorization – No More Loops!

 NumPy avoids loops by applying operations to entire arrays at once using SIMD
 (Single Instruction, Multiple Data) and other low-level optimizations. SIMD is a
 CPU-level optimization provided by modern processors

In [ ]:
listNumbers = [1, 2, 3, 4, 5]

list_squares = [x**2 for x in listNumbers]

print("List comprehension result:", list_squares)


# using NumPy for the same operation
arrNumbers = np.array(listNumbers)

arr_squares = arrNumbers**2
print("NumPy array operation result:", arr_squares)

List comprehension result: [1, 4, 9, 16, 25]
NumPy array operation result: [ 1  4  9 16 25]


## Exercises for Practice

1. Create a NumPy array with values from 10 to 100 and print its shape.
2. Compare the time taken to multiply two Python lists vs. two NumPy arrays.
3. Find the memory size of a NumPy array with 1 million elements.

In [13]:
arr =np.array(range(10,101))

print("Array with values from 10 to 100:", arr)
print("Shape of the array:", arr.shape)

Array with values from 10 to 100: [ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
Shape of the array: (91,)


In [14]:
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result = [x * y for x, y in zip(list1, list2)] # result = [0+0, 1+1, 2+2, ..., 999999+999999]
end = time.time()

print("Python list multiplication time:", end - start)


 # NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)
start = time.time()
result = arr1 * arr2  # Vectorized operation , result = [0+0, 1+1, 2+2, ..., 999999+999999]
end = time.time()
print("NumPy array multiplication time:", end - start)

Python list multiplication time: 0.1408381462097168
NumPy array multiplication time: 0.01766371726989746
