# Gauss-Jordan Elimination

Gauss-Jordan Elimination is an extension of Gauss Elimination where:
- We eliminate both **below and above** the pivot.
- We convert the matrix `A` into the **Identity matrix (I)**.
- This directly gives us the **solution vector x** or the **inverse of A**, depending on how it's applied.

---

## Use Cases:
- Solving Ax = b **without back-substitution**.
- Computing the **inverse of a matrix**.
- Getting matrix into **reduced row echelon form (RREF)**.


In [1]:
import numpy as np

def gaussJordanSolve(A, b):
    """
    Solves Ax = b using Gauss-Jordan Elimination.

    Parameters:
        A : numpy.ndarray (n x n)
        b : numpy.ndarray (n)

    Returns:
        x : numpy.ndarray (n)
    """
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)

    for pivot in range(n):
        # Normalize pivot row
        if A[pivot, pivot] == 0:
            raise ZeroDivisionError(f"Zero pivot encountered at row {pivot}")

        pivot_val = A[pivot, pivot]
        A[pivot, :] /= pivot_val
        b[pivot] /= pivot_val
        print(f"\nNormalizing pivot row {pivot}")
        print("A:", A)
        print("b:", b)

        # Eliminate all other rows
        for row in range(n):
            if row != pivot:
                multiplier = A[row, pivot]
                A[row, :] -= multiplier * A[pivot, :]
                b[row] -= multiplier * b[pivot]
                print(f"\nEliminating row {row} using pivot row {pivot}")
                print("Multiplier:", multiplier)
                print("Updated A:", A[row])
                print("Updated b:", b[row])

    return b  # A should be identity; b now contains the solution


## Matrix Inversion using Gauss-Jordan

To find the inverse of a matrix A:

1. Augment A with identity matrix → (A | I)
2. Apply Gauss-Jordan elimination to reduce A to identity
3. The transformed identity becomes A⁻¹

Only possible if A is **non-singular**.


In [2]:
def gaussJordanInverse(A):
    """
    Returns the inverse of matrix A using Gauss-Jordan elimination.

    Parameters:
        A : numpy.ndarray (n x n)

    Returns:
        A_inv : numpy.ndarray (n x n)
    """
    n = A.shape[0]
    A = A.astype(float)
    I = np.identity(n)
    
    # Augmented matrix [A | I]
    Aug = np.hstack((A, I))

    for pivot in range(n):
        # Normalize pivot row
        if Aug[pivot, pivot] == 0:
            raise ZeroDivisionError(f"Zero pivot at row {pivot}, try row swapping.")
        
        Aug[pivot, :] /= Aug[pivot, pivot]
        print(f"\nNormalized pivot row {pivot}:")
        print(Aug)

        # Eliminate other rows
        for row in range(n):
            if row != pivot:
                multiplier = Aug[row, pivot]
                Aug[row, :] -= multiplier * Aug[pivot, :]
                print(f"\nEliminated row {row} using row {pivot}:")
                print(Aug)

    # The right half is now the inverse
    A_inv = Aug[:, n:]
    return A_inv


## Example: Solve Ax = b and Find A⁻¹

Let:
A = [[2, 1, 1],
[1, 3, 2],
[1, 0, 0]]

b = [4, 5, 6]



We will:
- Solve `Ax = b` using Gauss-Jordan Elimination
- Compute `A⁻¹` using the augmented matrix


In [3]:
A = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [1, 0, 0]
])

b = np.array([4, 5, 6])

x = gaussJordanSolve(A.copy(), b.copy())
print("\n Solution x (Gauss-Jordan):")
print(x)

A_inv = gaussJordanInverse(A.copy())
print("\n Inverse of A:")
print(A_inv)

# Check A * A_inv = I
print("\nCheck A * A⁻¹ ≈ I:")
print(np.round(np.dot(A, A_inv), 4))



Normalizing pivot row 0
A: [[1.  0.5 0.5]
 [1.  3.  2. ]
 [1.  0.  0. ]]
b: [2. 5. 6.]

Eliminating row 1 using pivot row 0
Multiplier: 1.0
Updated A: [0.  2.5 1.5]
Updated b: 3.0

Eliminating row 2 using pivot row 0
Multiplier: 1.0
Updated A: [ 0.  -0.5 -0.5]
Updated b: 4.0

Normalizing pivot row 1
A: [[ 1.   0.5  0.5]
 [ 0.   1.   0.6]
 [ 0.  -0.5 -0.5]]
b: [2.  1.2 4. ]

Eliminating row 0 using pivot row 1
Multiplier: 0.5
Updated A: [1.  0.  0.2]
Updated b: 1.4

Eliminating row 2 using pivot row 1
Multiplier: -0.5
Updated A: [ 0.   0.  -0.2]
Updated b: 4.6

Normalizing pivot row 2
A: [[ 1.   0.   0.2]
 [ 0.   1.   0.6]
 [-0.  -0.   1. ]]
b: [  1.4   1.2 -23. ]

Eliminating row 0 using pivot row 2
Multiplier: 0.2
Updated A: [1. 0. 0.]
Updated b: 6.0

Eliminating row 1 using pivot row 2
Multiplier: 0.6
Updated A: [0. 1. 0.]
Updated b: 14.999999999999996

 Solution x (Gauss-Jordan):
[  6.  15. -23.]

Normalized pivot row 0:
[[1.  0.5 0.5 0.5 0.  0. ]
 [1.  3.  2.  0.  1.  0. ]
 [1.  0