## Crout's LU Decomposition Method

In Crout's method, a square matrix **A** is decomposed into two matrices:
- **L** (lower triangular matrix): Diagonal and lower elements are filled
- **U** (upper triangular matrix): Diagonal elements are set to 1, upper elements are computed

We solve a system of linear equations **Ax = b** by:
1. Decomposing A into L and U using Crout's method.
2. Solving **Ly = b** using forward substitution.
3. Solving **Ux = y** using backward substitution.

Let’s walk through the full Python implementation.


In [1]:
import numpy as np

## Step 1: Crout’s LU Decomposition Function

This function decomposes a matrix `A` into a lower triangular matrix `L` and an upper triangular matrix `U` such that `A = LU`.

Note: Diagonal elements of `U` are 1 by definition in Crout’s method.


In [2]:
def crout_decomposition(matrix):
    """
    Perform Crout's LU Decomposition on a given square matrix.
    Returns lower matrix L and upper matrix U such that A = LU.
    """

    number_of_rows = len(matrix)
    L = np.zeros((number_of_rows, number_of_rows))
    U = np.identity(number_of_rows)  # U will have 1s on the diagonal

    for j in range(number_of_rows):
        for i in range(j, number_of_rows):
            # Compute L[i][j]
            sum_ = 0
            for k in range(j):
                sum_ += L[i][k] * U[k][j]
            L[i][j] = matrix[i][j] - sum_

        for i in range(j + 1, number_of_rows):
            # Compute U[j][i]
            sum_ = 0
            for k in range(j):
                sum_ += L[j][k] * U[k][i]
            U[j][i] = (matrix[j][i] - sum_) / L[j][j]

    print("Lower Triangular Matrix L:\n", L)
    print("\nUpper Triangular Matrix U:\n", U)
    
    return L, U


## Step 2: Solve Ly = b using Forward Substitution
## Step 3: Solve Ux = y using Backward Substitution


In [3]:
def forward_substitution(L, b):
    """Solve Ly = b for y"""
    n = len(b)
    y = np.zeros(n)

    for i in range(n):
        sum_ = sum(L[i][j] * y[j] for j in range(i))
        y[i] = (b[i] - sum_) / L[i][i]

    print("\nSolution of Ly = b (Forward Substitution):\n", y)
    return y


def backward_substitution(U, y):
    """Solve Ux = y for x"""
    n = len(y)
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        sum_ = sum(U[i][j] * x[j] for j in range(i + 1, n))
        x[i] = y[i] - sum_

    print("\nSolution of Ux = y (Backward Substitution):\n", x)
    return x


## Step 4: Solve Ax = b using Crout’s LU Decomposition


In [4]:
def solve_using_crout(matrix, b):
    """
    Solve the system Ax = b using Crout's method
    """

    print("Original Matrix A:\n", matrix)
    print("Right-hand side vector b:\n", b)

    # Decompose A into L and U
    L, U = crout_decomposition(matrix)

    # Solve Lz = b using forward substitution
    y = forward_substitution(L, b)

    # Solve Ux = y using backward substitution
    x = backward_substitution(U, y)

    return x


In [5]:
A = np.array([
    [2, -1, 1],
    [3, 3, 9],
    [3, 3, 5]
], dtype=float)

b = np.array([2, -1, 4], dtype=float)

solution = solve_using_crout(A, b)
print("\nFinal Solution x:\n", solution)


Original Matrix A:
 [[ 2. -1.  1.]
 [ 3.  3.  9.]
 [ 3.  3.  5.]]
Right-hand side vector b:
 [ 2. -1.  4.]
Lower Triangular Matrix L:
 [[ 2.   0.   0. ]
 [ 3.   4.5  0. ]
 [ 3.   4.5 -4. ]]

Upper Triangular Matrix U:
 [[ 1.         -0.5         0.5       ]
 [ 0.          1.          1.66666667]
 [ 0.          0.          1.        ]]

Solution of Ly = b (Forward Substitution):
 [ 1.         -0.88888889 -1.25      ]

Solution of Ux = y (Backward Substitution):
 [ 2.22222222  1.19444444 -1.25      ]

Final Solution x:
 [ 2.22222222  1.19444444 -1.25      ]
