# Doolittle's LU Decomposition Method to Solve Ax = b

This notebook demonstrates how to solve a linear system `Ax = b` using **LU Decomposition** via the **Doolittle Algorithm**.

### What is Doolittle's Algorithm?
- It decomposes the matrix `A` into `L` and `U` such that:  
  **A = L * U**
- In **Doolittle**, the diagonal elements of `L` are `1`.
- We then solve:
  - `Lz = b` using forward substitution
  - `Ux = z` using backward substitution

This is efficient and avoids direct matrix inversion.


In [1]:
import numpy as np

In [4]:

def doolittle_lu_decomposition(matrix):
    """
    Performs LU decomposition using Doolittle's method.
    The matrix is decomposed into L and U such that A = L * U,
    where L has unit diagonal elements.
    """
    n = len(matrix)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    print("Starting Doolittle LU Decomposition...\n")

    for i in range(n):
        # Constructing U
        for k in range(i, n):
            sum_upper = sum(L[i][j] * U[j][k] for j in range(i))
            U[i][k] = matrix[i][k] - sum_upper

        # Constructing L
        L[i][i] = 1  # Diagonal elements are 1
        for k in range(i + 1, n):
            sum_lower = sum(L[k][j] * U[j][i] for j in range(i))
            L[k][i] = (matrix[k][i] - sum_lower) / U[i][i]

    print("Decomposition Complete ✅\n")
    print("Lower Triangular Matrix (L):\n", L)
    print("\nUpper Triangular Matrix (U):\n", U)

    return L, U


In [5]:
def forward_substitution(L, b):
    """
    Solves Lz = b using forward substitution.
    """
    n = len(b)
    z = np.zeros(n)

    print("\nSolving Lz = b using Forward Substitution...")

    for i in range(n):
        sum_val = sum(L[i][j] * z[j] for j in range(i))
        z[i] = b[i] - sum_val
        print(f"z[{i}] = {z[i]}")

    return z


In [6]:
def backward_substitution(U, z):
    """
    Solves Ux = z using backward substitution.
    """
    n = len(z)
    x = np.zeros(n)

    print("\nSolving Ux = z using Backward Substitution...")

    for i in range(n-1, -1, -1):
        sum_val = sum(U[i][j] * x[j] for j in range(i+1, n))
        x[i] = (z[i] - sum_val) / U[i][i]
        print(f"x[{i}] = {x[i]}")

    return x


In [7]:
# Define A and b
A = np.array([[2.0, -1.0, 1.0],
              [3.0, 3.0, 9.0],
              [3.0, 3.0, 5.0]])

b = np.array([2.0, -1.0, 4.0])

print("Input Matrix A:\n", A)
print("\nRight-hand side vector b:\n", b)

# LU Decomposition
L, U = doolittle_lu_decomposition(A)

# Solve Lz = b
z = forward_substitution(L, b)

# Solve Ux = z
x = backward_substitution(U, z)

print("\n✅ Final Solution x:\n", x)


Input Matrix A:
 [[ 2. -1.  1.]
 [ 3.  3.  9.]
 [ 3.  3.  5.]]

Right-hand side vector b:
 [ 2. -1.  4.]
Starting Doolittle LU Decomposition...

Decomposition Complete ✅

Lower Triangular Matrix (L):
 [[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]

Upper Triangular Matrix (U):
 [[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]

Solving Lz = b using Forward Substitution...
z[0] = 2.0
z[1] = -4.0
z[2] = 5.0

Solving Ux = z using Backward Substitution...
x[2] = -1.25
x[1] = 1.1944444444444444
x[0] = 2.2222222222222223

✅ Final Solution x:
 [ 2.22222222  1.19444444 -1.25      ]


# ✅ Conclusion

Using **Doolittle's LU Decomposition**, we efficiently solved the system **Ax = b** by:
1. Decomposing A into L and U.
2. Solving **Lz = b** using forward substitution.
3. Solving **Ux = z** using backward substitution.

This avoids direct matrix inversion and is numerically stable if the matrix is not singular or ill-conditioned.
